### ISSUE TITLE
Decide how the information exposed should be extended

### ISSUE THREAD

**Issue by mcupak** [ga4gh-discovery/ga4gh-service-info#10]
Some services, e.g. beacon, have an `info` field to specify arbitrary key value pairs (either strings or arbitrary JSON), which are not standardized. A slight advantage of this is being able to easily distinguish whether you're dealing with a standard or custom attribute, and there's a clear migration path for standardizing commonly used fields. We should decide if we want people to extend the metadata through such a field or add attributes at the top level.

One thing to consider is how tools for verifying API compatibility, such as dredd, treat both options.

**Comment by mcupak** [comment]
Andy: info not a good name

Miro: provide examples and document nested field vs. top-level

Preference for allowing arbitrary types rather than just strings.

**Comment by andrewyatz** [comment]
We had previously discussed the possibility to extend this model with a custom version. I've cooked up a few examples below from refget.

Inline representation:

```json
{
  "id": "org.ga4gh.service.refget",
  "name": "refget_reference_impl",
  "description": "Refget reference implementation",
  "documentationUrl": "https://samtools.github.io/hts-specs/refget.html",
  "contactUrl": "mailto:ga4gh-refget@ga4gh.org",
  "version": "1.0.0",
  "algorithms":["md5","trunc512","vmcdigest"],
  "circular_supported":true,
  "subsequence_limit":null,
}
```

Nested attributed version:

```json
{
  "id": "org.ga4gh.service.refget",
  "name": "refget_reference_impl",
  "description": "Refget reference implementation",
  "documentationUrl": "https://samtools.github.io/hts-specs/refget.html",
  "contactUrl": "mailto:ga4gh-refget@ga4gh.org",
  "version": "1.0.0",
  "extension" : {
    "algorithms":["md5","trunc512","vmcdigest"],
    "circular_supported":true,
    "subsequence_limit":null,
  }
}
```

I guess the only difference between these is how much a custom implementation is allowed control the keys used. Putting it into a sub object/hash does help the namespacing but does mean it's a wild-west. So long as providers could have the option to extend the model and then tighten up the responses then I think I'd be happy.

**Comment by mcupak** [comment]
Jordi+Andy+Miro: agreement on option 2

**Comment by mcupak** [comment]
To document why we've converged on Option 2 for future reference:

Option 1:
- This is a more natural way of extending.
- Uncertainty is tooling support - for example, if we have extra fields in an implementation of the specification, would tools for API compatibility verification (e.g. dredd) still consider them compatible?
- To distinguish between reserved and custom fields, you need to have the version of the specification. This can potentially be less clear for human readers, but does not make a difference to tools.

Option 2:
- The approach used in Beacon, worked well for a long time.
- Nicely human readable - can easily tell which fields are custom.
- An easy way of standardizing fields in future API versions - see what people put in the nested field, then move to the top level.
- No risks re tooling.
- It's a bit awkward to nest many things if your implementation adds a lot of custom fields.

The main reasons for going for Option 2 are clarity and backward compatibility. While we can guarantee backward compatibility with both options at the level of the standard (if we're only bumping a minor version, we'd only add fields, not change existing fields), a minor version bump in the spec might force a major version update in an implementation (adding a field someone is already using in a different way). The versions of the implementation and the spec are not tied together, so strictly speaking, this is not a problem, but we felt it's not a nice property.

**Comment by andrewyatz** [comment]
This can be closed
