### ISSUE TITLE
Describe the product on the Discovery website

### ISSUE THREAD

**Issue by mcupak** [ga4gh-discovery/ga4gh-service-info#15]
We've been asked to provide a description of this specification on the new [Discovery website](https://github.com/ga4gh-discovery/ga4gh-discovery.github.io).

**Comment by andrewyatz** [comment]
I assume this will be placed under discovery networks? Does service-info require a product or is it an intrinsic part of the network that to describe the endpoint is, in part, to describe the network? Sorry I'm  just not too clear is all.

**Comment by mcupak** [comment]
I'd say it's a product, i.e. our team has 2 products/standards - service info and service registry.

**Comment by andrewyatz** [comment]
Okay :). Does this go into schemablocks too?

**Comment by mcupak** [comment]
No.

**Comment by mcupak** [comment]
Updated: https://ga4gh-discovery.github.io/
