### ISSUE TITLE
PRC and Plenary feedback tasks

### ISSUE THREAD

**Issue by andrewyatz** [ga4gh-discovery/ga4gh-service-info#55]
- [x] Align with the CURIE namespace for types
- [x] Clarify how unique ID needs to be
- [x] Support authentication methods for services which need to do this
- [x] Clarify URL behaviour i.e. take `/service-info` off and you get to the API
- [x] Convert environment into a string, give example values, clarify the usage
- [x] Clarify error code usage in feedback to PRC
- [x] Change the type field into a type object. Allows use of the sub-values currently specified
- [x] How unique should type be? Fold into the review process
- [x] Does service-info require authentication
- [x] GA4GH logo. Include
- [x] How to support partial implementations of a specification

**Comment by mcupak** [comment]
This has been resolved, closing.
