### ISSUE TITLE
Extract type schema

### ISSUE THREAD

**Issue by mcupak** [ga4gh-discovery/ga4gh-service-info#59]
To better support https://github.com/ga4gh-discovery/ga4gh-service-registry/issues/94, it would be useful to extract the definition of type to a separate schema, so that we can refer to it directly instead of duplicating. I think such reusable schema will be useful for other APIs as well.

This is an internal change not affecting the API, and as such I'd like to add it to 1.0.

**Comment by mcupak** [comment]
@andrewyatz WDYT?

**Comment by andrewyatz** [comment]
Makes sense to me
