### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh-discovery/ga4gh-service-info#61]
In light of the product approval, can we get a tagged release to implement/link to 
Thanks!

**Comment by andrewyatz** [comment]
Awaiting #59 to be resolved before minting the v1 release

**Comment by mcupak** [comment]
@denis-yuen Yes! Here you go: https://github.com/ga4gh-discovery/ga4gh-service-info/releases/tag/v1.0.0.
